theme: jekyll-theme-minimal
title: "Snapp iOS Weekly"
company: "Snapp Technology"
url: "https://ios-newsletter.snappmobile.io"

collections:
  issues:
    output: true
    # permalink: /:collection/:name:output_ext
  pipeline:
    output: false  # We don't need individual pages, just a list
